### ISSUE TITLE
Implementación de pruebas unitarias del sistema de reconocimiento

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#10]
Se deben implementar las pruebas unitarias del sistema de reconocimiento de imágenes de crotales.

**Comment by luisfernandezjimenez** [comment]
Las pruebas unitarias deben cubrir todas las funciones del código.

**Comment by NToader** [comment]
No se va a cubrir la funcionalidad referente a interfaces y métodos para mostrar resultados en ventanas de OpenCV.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 4h
Tiempo real: 5h
