### ISSUE TITLE
Implementación Pruebas unitarias

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#12]
Se deben implementar las pruebas unitarias del servidor de aplicaciones.

**Comment by luisfernandezjimenez** [comment]
La complejidad de la implementación de estas pruebas es demasiado elevada.

No se van a llevar a cabo.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 1h
Tiempo real: - (no se ha realizado)
