### ISSUE TITLE
Implementación Pruebas unitarias

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#14]
Se debe implementar las pruebas unitarias de la funcionalidad desarrollada en JavaScript de la página web.

**Comment by luisfernandezjimenez** [comment]
Esta funcionalidad no es relevante de cara a la práctica, por tanto no se van a realizar pruebas unitarias.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 2h
Tiempo real: - (no se ha realizado)
