### ISSUE TITLE
Crear presentación

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#17]
Se debe crear la presentación que se utilizará para mostrar el sistema a los compañeros.

**Comment by NToader** [comment]
El problema que se nos ha planteado en a la hora de realizar la presentación es que no podemos calcular todas las tasas para el análisis de resultados. Esto se debe a que en el problema de reconocimiento de crotales o se acierta o se falla, por tanto, en principio no hay True negatives ni False negatives. Suponiendo que los casos en los que no se reconoce ningún carácter son False negatives, nos sigue faltando True negatives. Por ello, la curva ROC queda descartada ya que depende de esta tasa para el cálculo del False positive rate. 

En consecuencia, deberíamos utilizar la curva de Precision Recall, pero esto tampoco se puede realizar, puesto que no tenemos un umbral que variar para cambiar el comportamiento del sistema. 

???

**Comment by NToader** [comment]
Finalmente, se modificó el código para introducir la confianza devuelta por Tesseract para poder realizar la curva Precision Recall.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 8h
Tiempo empleado: 5h
