### ISSUE TITLE
Diseñar Sistema de reconocimiento

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#5]
Se deben generar los distintos diagramas para el diseño del sistema de reconocimiento.

**Comment by luisfernandezjimenez** [comment]
Para diseñar el sistema deberíamos crear las clases en base a los 4 bloques de funcionalidad principales: localización de texto, reconocimiento de texto, reconocimiento de crotales y encapsulamiento del crotal.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 4h
Tiempo real: 3h
