### ISSUE TITLE
Diseñar Servidor HTTP

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#6]
Se deben generar los distintos diagramas para el diseño del servidor de aplicaciones.

**Comment by luisfernandezjimenez** [comment]
Al ser un sistema relativamente simple basta con definir un servidor en flask que acepte peticiones REST y sirva contenido estático en consecuencia no es necesario realizar un diseño para esta parte.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 4h
Tiempo real: - (no se ha realizado)
