### ISSUE TITLE
Diseñar la página web

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#7]
Se deben generar los distintos diagramas para el diseño de la página web.

**Comment by luisfernandezjimenez** [comment]
La funcionalidad de la página web es simple, por tanto no se va a realizar de esta parte.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 4h
Tiempo real: 30min (se optó por dejar el código como funciones)
