### ISSUE TITLE
Desarrollo del entregable

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#8]
Se debe desarrollar el documento de la entrega de diseños.

**Comment by NToader** [comment]
El código de la entrega está listo, solo hay redactar la memoria y generar las imágenes del algoritmo para incluir en los diagramas.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 10h
Tiempo real: 12h
