### ISSUE TITLE
Implementación Sistema de reconocimiento

### ISSUE THREAD

**Issue by luisfernandezjimenez** [NToader/AIVA-Crotalpath#9]
Se debe implementar el sistema de reconocimiento de imágenes de crotales.

**Comment by luisfernandezjimenez** [comment]
Siguiendo la división realizada en clases en la fase de diseño se debe implementar el algorítmo de visión.

**Comment by NToader** [comment]
Tiempo estimado para el desarrollo de la tarea: 40h
Tiempo real: 17h (la correcta documentación y pylint ampliaron el tiempo de desarrollo)
